djangogoat/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.views.generic import TemplateView
from django.views.static import serve
from django.urls import (
    include,
    path,
    re_path,
)

from authentication import views as auth_views
from notes import views as notes_views


urlpatterns = [
    path('admin/', admin.site.urls),

    # Notes pages
    path('dash/', notes_views.dash, name='dash'),
    path(
        'conversation/<friend_pk>',
        notes_views.conversation,
        name='conversation'
    ),
    path('note/<pk>', notes_views.note, name='note'),
    path('write-note/', notes_views.write_note, name='write-note'),

    # Unauthenticated pages
    path('vulnerabilities',
         TemplateView.as_view(template_name='vulnerabilities.html'),
         name='vulnerabilities'),
    path(
        '',
        TemplateView.as_view(template_name='landing.html'),
        name='landing'
    ),
    path(
        'instructions',
        TemplateView.as_view(template_name='instructions.html'),
        name='instructions'
    ),

    # Authentication and user management pages
    path('login/', auth_views.log_in, name='login'),
    path('logout/', logout_then_login, {'login_url': 'login'}, name='logout'),
    path('profile/<pk>', auth_views.profile, name='profile'),
    path('profile-update', auth_views.profile_update, name='profile-update'),
    path('sign-up/', auth_views.sign_up, name='sign-up'),
    path('', include('django.contrib.auth.urls')),

    # Media files
    re_path(
        r'^media/(?P<path>.*)$',
        serve,
        {'document_root': settings.MEDIA_ROOT}
    ),
]

authentication/models.py
import os

from django.db import models


def upload_path(user, filename):
    extension = os.path.splitext(filename)[1]
    return 'avatar_%s%s' % (user.pk, extension)


class UserProfile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to=upload_path, blank=True)
    bio = models.TextField(max_length=255, blank=True)
    cleartext_password = models.TextField(max_length=255)

authentication/forms.py
from django import forms

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'bio')
        widgets = {
            'avatar': forms.FileInput(),
            'bio': forms.Textarea(attrs={'rows': 5}),
        }

authentication/views.py
from django.contrib.auth import (
    authenticate,
    login,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)

from common.decorators import public
from .forms import UserProfileForm
from .models import UserProfile


@public
def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            UserProfile.objects.create(
                user=new_user,
                cleartext_password=raw_password,
            )
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('profile', pk=user.pk)
    else:
        form = UserCreationForm()

    return render(request, 'sign_up.html', {'form': form})


@public
def log_in(request):
    error = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        query = (
            """
            SELECT * FROM auth_user
               INNER JOIN authentication_userprofile
               ON auth_user.id = authentication_userprofile.user_id
            WHERE username = '%s'
            AND authentication_userprofile.cleartext_password = '%s';
            """
            % (username, password)
        )
        try:
            user = User.objects.raw(query)[0]
        except IndexError:
            user = None
        if user:
            login(request, user)
            return redirect('dash')
        else:
            error = 'The credentials you entered are not valid. Try again.'

    return render(request, 'login.html', {'error': error})


@login_required
def profile_update(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(
            request.POST,
            request.FILES,
            instance=user.userprofile
        )
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            return redirect('profile', pk=user.pk)
    else:
        form = UserProfileForm(instance=user.userprofile)

    return render(request, 'profile_update.html', {
     'form': form,
     'user': user,
    })


def profile(request, pk):
    target_user = get_object_or_404(User, pk=pk)

    return render(request, 'profile.html', {'target_user': target_user})

authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block pagename %}Log In{% endblock pagename %}


{% block content %}
<form method='post' class="pa4 black-80 measure center">
  <fieldset id="sign_up" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Log In</legend>
    <small id="error" class="f6 black-60 db mv2">
      {{ error }}
    </small>
  {% csrf_token %}
  <div class='mt3'>
    <label for='id_username' class="db fw6 lh-copy f6">Username</label>
    <input type='text' id='id_username' name='username'
      class="b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2"
      required autofocus>
  </div>
  <div class='mt3'>
    <label for='id_password' class="db fw6 lh-copy f6">Password</label>
    <input type='password' id='id_password' name='password'
      class="b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2"
      autocomplete='off' required>
  </div>
  <div class="">
    <button class="b ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id="login_button" type="submit">
      Log in
    </button>
  </div>
</form>
{% endblock content %}

authentication/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block pagename %}Profile {% endblock pagename %}


{% block content %}
<article class="w-third-l w-50-m w-100 center br3 pa3 pa4-ns mv3 ba b--white-30">
  <div class="tc">
    {% if target_user.userprofile.avatar %}
    <img src="{% get_media_prefix %}{{ target_user.userprofile.avatar }}"
        class="br-100 h4 w4 dib" title="picture of a goat">
    {% else %}
    <img src="/static/unknown_goat.png" class="br-100 h4 w4 dib"
      title="Black shillouette of a goat with a pink question mark">
    {% endif %}
    <h1 class="f4">{{ target_user.username }}</h1>
    <hr class="mw3 bb bw1 b--white-40">
  <p class="lh-copy measure center f6 black-70">
    {{ target_user.userprofile.bio }}
  </p>
  {% if target_user == request.user %}
    <a class="center tc mt2 f7 link bg-animate white hover-near-black hover-bg-lightest-blue dib pv2 ph3 br-pill ba b--white-20"
       href="{% url 'profile-update' %}">Edit Profile</a>
  {% endif %}
</div>
</article>
{% endblock content %}

authentication/templates/profile_update.html
{% extends 'base.html' %}
{% load setclass %}

{% block pagename %}Profile Update{% endblock pagename %}

{% block content %}
<form enctype='multipart/form-data' method='post'
  class="pa4 black-80 measure center">
  <fieldset id="profile" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Profile update</legend>
  {% csrf_token %}
  <div class='mt3 w-100'>
    <label for='id_avatar' class="db fw6 lh-copy f6">Avatar</label>
      {{ form.avatar | setclass:'w-100 mb2'}}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
    </div>
  </div>
  <div class='mt3'>
    <label for='id_bio' class="db fw6 lh-copy f6">Bio</label>
      {{ form.bio | setclass:'db border-box w-100 measure ba b--white-40 pa2 mb2'}}
      {% for error in field.errors %}
        <small id="name-desc" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class="">
    <input class="b mt2 ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id='update' type="submit" value="Update">
  </div>
</form>
{% endblock content %}

authentication/templates/sign_up.html
{% extends 'base.html' %}
{% load setclass %}
{% block pagename %}Sign Up{% endblock pagename %}


{% block content %}
<form method='post' class="pa4 black-80 measure center">
  <fieldset id="sign_up" class="ba b--transparent ph0 mh0">
    <legend class="f4 fw6 ph0 mh0">Sign Up</legend>
  {% csrf_token %}
  <div class='mt3'>
    <label for='username' class="db fw6 lh-copy f6">Username</label>
      {{ form.username |setclass:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.username.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class='mt3'>
    <label for='id_password1' class="db fw6 lh-copy f6">Password</label>
      {{ form.password1|setclass:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.password1.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class='mt3'>
    <label for='id_password2' class="db fw6 lh-copy f6">Password Confirmation</label>
      {{ form.password2|setclass:'b pa2 input-reset ba bg-transparent hover-bg-white w-100 mb2' }}
      {% for error in form.password2.errors %}
        <small id="error" class="f6 black-60 db mv2">
          {{ error }}
        </small>
      {% endfor %}
  </div>
  <div class="">
    <input class="b mt2 ph3 pv2 input-reset ba b--black bg-transparent grow pointer f6 dib"
      id='submit_button' type="submit" value="Sign Up">
  </div>
</form>
{% endblock content %}